server:
  port: 8080
#  servlet:
 #   context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://antonio-dev.go.ro:16433/gymmanagement
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://antonio-dev.go.ro:8081/keycloak-app/realms/gym-management-realm


keycloak:
  realm: gym-management-realm
  resource: gym-management-backend
 # auth-server-url: http://antonio-dev.go.ro:8081/keycloack-app/realms/gym-management-realm/protocol/openid-connect/auth
  auth-server-url: http://antonio-dev.go.ro:8081/keycloak-app/
  credentials:
    secret: KimbunOU9OVJaAU9HIpZHJ7fUsICh2gV
  admin:
    username: admin
    password: admin

stripe:
  api-key: your_stripe_secret_key
  webhook-secret: your_stripe_webhook_secret

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

cors:
  allowedOrigins: 'http://localhost:3000'
